//go:build amd64

package hex

// decodeBlocksSSE (32 src chars -> 16 bytes per block) and decodeBlocksAVX2
// (64 -> 32) are the vectorised hex decoders. Generated by go-asmgen
// (decode_gen.go), in decode_amd64.s. Each attempts n blocks and returns the
// number of blocks fully decoded before the first block containing an invalid
// char (== n when every attempted block is valid); the caller resumes a scalar
// encoding/hex-style loop from there so the error offset is bit-exact.
func decodeBlocksSSE(dst, src []byte, n int) int
func decodeBlocksAVX2(dst, src []byte, n int) int

// decodeSIMD decodes whole 32- or 64-char blocks of src into dst with the
// widest available kernel, returning the bytes written to dst and consumed from
// src. It stops at the first block containing an invalid char (so the caller's
// scalar tail produces the exact InvalidByteError offset) and never reads or
// writes a partial trailing block.
func decodeSIMD(dst, src []byte) (dstDone, srcDone int) {
	if hasAVX2 && len(src) >= 64 {
		blocks := len(src) / 64
		done := decodeBlocksAVX2(dst, src, blocks)
		return done * 32, done * 64
	}
	if len(src) >= 32 {
		blocks := len(src) / 32
		done := decodeBlocksSSE(dst, src, blocks)
		return done * 16, done * 32
	}
	return 0, 0
}
