// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·decodeBlocksVX(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	MOVD $0, R4
	CMPBEQ R3, $0, dret
	MOVD $z_c0lo<>+0(SB), R5
	VL (R5), V8
	MOVD $z_c9hi<>+0(SB), R5
	VL (R5), V9
	MOVD $z_cUlo<>+0(SB), R5
	VL (R5), V10
	MOVD $z_cUhi<>+0(SB), R5
	VL (R5), V11
	MOVD $z_cLlo<>+0(SB), R5
	VL (R5), V12
	MOVD $z_cLhi<>+0(SB), R5
	VL (R5), V13
	MOVD $z_subD<>+0(SB), R5
	VL (R5), V14
	MOVD $z_subU<>+0(SB), R5
	VL (R5), V15
	MOVD $z_subL<>+0(SB), R5
	VL (R5), V16
	MOVD $z_gHi<>+0(SB), R5
	VL (R5), V18
	MOVD $z_gLo<>+0(SB), R5
	VL (R5), V19
dloop:
	VL (R2), V0
	VL 16(R2), V1
	VZERO V20
	VCHLB V0, V8, V21
	VCHLB V9, V0, V22
	VN V21, V22, V21
	VCHLB V0, V10, V22
	VCHLB V11, V0, V23
	VN V22, V23, V22
	VCHLB V0, V12, V23
	VCHLB V13, V0, V24
	VN V23, V24, V23
	VO V21, V22, V24
	VO V24, V23, V24
	VNO V24, V24, V25
	VO V20, V25, V20
	VSB V14, V0, V26
	VN V26, V21, V26
	VSB V15, V0, V27
	VN V27, V22, V27
	VO V26, V27, V26
	VSB V16, V0, V27
	VN V27, V23, V27
	VO V26, V27, V26
	VLR V26, V0
	VCHLB V1, V8, V21
	VCHLB V9, V1, V22
	VN V21, V22, V21
	VCHLB V1, V10, V22
	VCHLB V11, V1, V23
	VN V22, V23, V22
	VCHLB V1, V12, V23
	VCHLB V13, V1, V24
	VN V23, V24, V23
	VO V21, V22, V24
	VO V24, V23, V24
	VNO V24, V24, V25
	VO V20, V25, V20
	VSB V14, V1, V26
	VN V26, V21, V26
	VSB V15, V1, V27
	VN V27, V22, V27
	VO V26, V27, V26
	VSB V16, V1, V27
	VN V27, V23, V27
	VO V26, V27, V26
	VLR V26, V1
	VLGVG $0, V20, R5
	VLGVG $1, V20, R6
	OR R6, R5, R5
	CMPBNE R5, $0, dret
	VPERM V0, V1, V18, V21
	VPERM V0, V1, V19, V22
	VESLB $4, V21, V21
	VO V21, V22, V21
	VST V21, (R1)
	ADD $32, R2
	ADD $16, R1
	ADD $1, R4
	CMPBNE R4, R3, dloop
dret:
	MOVD R4, ret+56(FP)
	RET

DATA z_c0lo<>+0(SB)/1, $0x2f
DATA z_c0lo<>+1(SB)/1, $0x2f
DATA z_c0lo<>+2(SB)/1, $0x2f
DATA z_c0lo<>+3(SB)/1, $0x2f
DATA z_c0lo<>+4(SB)/1, $0x2f
DATA z_c0lo<>+5(SB)/1, $0x2f
DATA z_c0lo<>+6(SB)/1, $0x2f
DATA z_c0lo<>+7(SB)/1, $0x2f
DATA z_c0lo<>+8(SB)/1, $0x2f
DATA z_c0lo<>+9(SB)/1, $0x2f
DATA z_c0lo<>+10(SB)/1, $0x2f
DATA z_c0lo<>+11(SB)/1, $0x2f
DATA z_c0lo<>+12(SB)/1, $0x2f
DATA z_c0lo<>+13(SB)/1, $0x2f
DATA z_c0lo<>+14(SB)/1, $0x2f
DATA z_c0lo<>+15(SB)/1, $0x2f
GLOBL z_c0lo<>(SB), RODATA|NOPTR, $16

DATA z_c9hi<>+0(SB)/1, $0x3a
DATA z_c9hi<>+1(SB)/1, $0x3a
DATA z_c9hi<>+2(SB)/1, $0x3a
DATA z_c9hi<>+3(SB)/1, $0x3a
DATA z_c9hi<>+4(SB)/1, $0x3a
DATA z_c9hi<>+5(SB)/1, $0x3a
DATA z_c9hi<>+6(SB)/1, $0x3a
DATA z_c9hi<>+7(SB)/1, $0x3a
DATA z_c9hi<>+8(SB)/1, $0x3a
DATA z_c9hi<>+9(SB)/1, $0x3a
DATA z_c9hi<>+10(SB)/1, $0x3a
DATA z_c9hi<>+11(SB)/1, $0x3a
DATA z_c9hi<>+12(SB)/1, $0x3a
DATA z_c9hi<>+13(SB)/1, $0x3a
DATA z_c9hi<>+14(SB)/1, $0x3a
DATA z_c9hi<>+15(SB)/1, $0x3a
GLOBL z_c9hi<>(SB), RODATA|NOPTR, $16

DATA z_cUlo<>+0(SB)/1, $0x40
DATA z_cUlo<>+1(SB)/1, $0x40
DATA z_cUlo<>+2(SB)/1, $0x40
DATA z_cUlo<>+3(SB)/1, $0x40
DATA z_cUlo<>+4(SB)/1, $0x40
DATA z_cUlo<>+5(SB)/1, $0x40
DATA z_cUlo<>+6(SB)/1, $0x40
DATA z_cUlo<>+7(SB)/1, $0x40
DATA z_cUlo<>+8(SB)/1, $0x40
DATA z_cUlo<>+9(SB)/1, $0x40
DATA z_cUlo<>+10(SB)/1, $0x40
DATA z_cUlo<>+11(SB)/1, $0x40
DATA z_cUlo<>+12(SB)/1, $0x40
DATA z_cUlo<>+13(SB)/1, $0x40
DATA z_cUlo<>+14(SB)/1, $0x40
DATA z_cUlo<>+15(SB)/1, $0x40
GLOBL z_cUlo<>(SB), RODATA|NOPTR, $16

DATA z_cUhi<>+0(SB)/1, $0x47
DATA z_cUhi<>+1(SB)/1, $0x47
DATA z_cUhi<>+2(SB)/1, $0x47
DATA z_cUhi<>+3(SB)/1, $0x47
DATA z_cUhi<>+4(SB)/1, $0x47
DATA z_cUhi<>+5(SB)/1, $0x47
DATA z_cUhi<>+6(SB)/1, $0x47
DATA z_cUhi<>+7(SB)/1, $0x47
DATA z_cUhi<>+8(SB)/1, $0x47
DATA z_cUhi<>+9(SB)/1, $0x47
DATA z_cUhi<>+10(SB)/1, $0x47
DATA z_cUhi<>+11(SB)/1, $0x47
DATA z_cUhi<>+12(SB)/1, $0x47
DATA z_cUhi<>+13(SB)/1, $0x47
DATA z_cUhi<>+14(SB)/1, $0x47
DATA z_cUhi<>+15(SB)/1, $0x47
GLOBL z_cUhi<>(SB), RODATA|NOPTR, $16

DATA z_cLlo<>+0(SB)/1, $0x60
DATA z_cLlo<>+1(SB)/1, $0x60
DATA z_cLlo<>+2(SB)/1, $0x60
DATA z_cLlo<>+3(SB)/1, $0x60
DATA z_cLlo<>+4(SB)/1, $0x60
DATA z_cLlo<>+5(SB)/1, $0x60
DATA z_cLlo<>+6(SB)/1, $0x60
DATA z_cLlo<>+7(SB)/1, $0x60
DATA z_cLlo<>+8(SB)/1, $0x60
DATA z_cLlo<>+9(SB)/1, $0x60
DATA z_cLlo<>+10(SB)/1, $0x60
DATA z_cLlo<>+11(SB)/1, $0x60
DATA z_cLlo<>+12(SB)/1, $0x60
DATA z_cLlo<>+13(SB)/1, $0x60
DATA z_cLlo<>+14(SB)/1, $0x60
DATA z_cLlo<>+15(SB)/1, $0x60
GLOBL z_cLlo<>(SB), RODATA|NOPTR, $16

DATA z_cLhi<>+0(SB)/1, $0x67
DATA z_cLhi<>+1(SB)/1, $0x67
DATA z_cLhi<>+2(SB)/1, $0x67
DATA z_cLhi<>+3(SB)/1, $0x67
DATA z_cLhi<>+4(SB)/1, $0x67
DATA z_cLhi<>+5(SB)/1, $0x67
DATA z_cLhi<>+6(SB)/1, $0x67
DATA z_cLhi<>+7(SB)/1, $0x67
DATA z_cLhi<>+8(SB)/1, $0x67
DATA z_cLhi<>+9(SB)/1, $0x67
DATA z_cLhi<>+10(SB)/1, $0x67
DATA z_cLhi<>+11(SB)/1, $0x67
DATA z_cLhi<>+12(SB)/1, $0x67
DATA z_cLhi<>+13(SB)/1, $0x67
DATA z_cLhi<>+14(SB)/1, $0x67
DATA z_cLhi<>+15(SB)/1, $0x67
GLOBL z_cLhi<>(SB), RODATA|NOPTR, $16

DATA z_subD<>+0(SB)/1, $0x30
DATA z_subD<>+1(SB)/1, $0x30
DATA z_subD<>+2(SB)/1, $0x30
DATA z_subD<>+3(SB)/1, $0x30
DATA z_subD<>+4(SB)/1, $0x30
DATA z_subD<>+5(SB)/1, $0x30
DATA z_subD<>+6(SB)/1, $0x30
DATA z_subD<>+7(SB)/1, $0x30
DATA z_subD<>+8(SB)/1, $0x30
DATA z_subD<>+9(SB)/1, $0x30
DATA z_subD<>+10(SB)/1, $0x30
DATA z_subD<>+11(SB)/1, $0x30
DATA z_subD<>+12(SB)/1, $0x30
DATA z_subD<>+13(SB)/1, $0x30
DATA z_subD<>+14(SB)/1, $0x30
DATA z_subD<>+15(SB)/1, $0x30
GLOBL z_subD<>(SB), RODATA|NOPTR, $16

DATA z_subU<>+0(SB)/1, $0x37
DATA z_subU<>+1(SB)/1, $0x37
DATA z_subU<>+2(SB)/1, $0x37
DATA z_subU<>+3(SB)/1, $0x37
DATA z_subU<>+4(SB)/1, $0x37
DATA z_subU<>+5(SB)/1, $0x37
DATA z_subU<>+6(SB)/1, $0x37
DATA z_subU<>+7(SB)/1, $0x37
DATA z_subU<>+8(SB)/1, $0x37
DATA z_subU<>+9(SB)/1, $0x37
DATA z_subU<>+10(SB)/1, $0x37
DATA z_subU<>+11(SB)/1, $0x37
DATA z_subU<>+12(SB)/1, $0x37
DATA z_subU<>+13(SB)/1, $0x37
DATA z_subU<>+14(SB)/1, $0x37
DATA z_subU<>+15(SB)/1, $0x37
GLOBL z_subU<>(SB), RODATA|NOPTR, $16

DATA z_subL<>+0(SB)/1, $0x57
DATA z_subL<>+1(SB)/1, $0x57
DATA z_subL<>+2(SB)/1, $0x57
DATA z_subL<>+3(SB)/1, $0x57
DATA z_subL<>+4(SB)/1, $0x57
DATA z_subL<>+5(SB)/1, $0x57
DATA z_subL<>+6(SB)/1, $0x57
DATA z_subL<>+7(SB)/1, $0x57
DATA z_subL<>+8(SB)/1, $0x57
DATA z_subL<>+9(SB)/1, $0x57
DATA z_subL<>+10(SB)/1, $0x57
DATA z_subL<>+11(SB)/1, $0x57
DATA z_subL<>+12(SB)/1, $0x57
DATA z_subL<>+13(SB)/1, $0x57
DATA z_subL<>+14(SB)/1, $0x57
DATA z_subL<>+15(SB)/1, $0x57
GLOBL z_subL<>(SB), RODATA|NOPTR, $16

DATA z_gHi<>+0(SB)/1, $0x00
DATA z_gHi<>+1(SB)/1, $0x02
DATA z_gHi<>+2(SB)/1, $0x04
DATA z_gHi<>+3(SB)/1, $0x06
DATA z_gHi<>+4(SB)/1, $0x08
DATA z_gHi<>+5(SB)/1, $0x0a
DATA z_gHi<>+6(SB)/1, $0x0c
DATA z_gHi<>+7(SB)/1, $0x0e
DATA z_gHi<>+8(SB)/1, $0x10
DATA z_gHi<>+9(SB)/1, $0x12
DATA z_gHi<>+10(SB)/1, $0x14
DATA z_gHi<>+11(SB)/1, $0x16
DATA z_gHi<>+12(SB)/1, $0x18
DATA z_gHi<>+13(SB)/1, $0x1a
DATA z_gHi<>+14(SB)/1, $0x1c
DATA z_gHi<>+15(SB)/1, $0x1e
GLOBL z_gHi<>(SB), RODATA|NOPTR, $16

DATA z_gLo<>+0(SB)/1, $0x01
DATA z_gLo<>+1(SB)/1, $0x03
DATA z_gLo<>+2(SB)/1, $0x05
DATA z_gLo<>+3(SB)/1, $0x07
DATA z_gLo<>+4(SB)/1, $0x09
DATA z_gLo<>+5(SB)/1, $0x0b
DATA z_gLo<>+6(SB)/1, $0x0d
DATA z_gLo<>+7(SB)/1, $0x0f
DATA z_gLo<>+8(SB)/1, $0x11
DATA z_gLo<>+9(SB)/1, $0x13
DATA z_gLo<>+10(SB)/1, $0x15
DATA z_gLo<>+11(SB)/1, $0x17
DATA z_gLo<>+12(SB)/1, $0x19
DATA z_gLo<>+13(SB)/1, $0x1b
DATA z_gLo<>+14(SB)/1, $0x1d
DATA z_gLo<>+15(SB)/1, $0x1f
GLOBL z_gLo<>(SB), RODATA|NOPTR, $16

