// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·decodeBlocksSSE(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	XORQ BX, BX
	TESTQ CX, CX
	JZ sret
sloop:
	MOVOU (SI), X0
	MOVOU 16(SI), X1
	PCMPEQB X15, X15
	PXOR X9, X9
	MOVO X0, X10
	MOVOU c0lo<>+0(SB), X11
	PCMPGTB X11, X10
	MOVOU c9hi<>+0(SB), X12
	PCMPGTB X0, X12
	PAND X12, X10
	MOVO X0, X12
	MOVOU cUlo<>+0(SB), X11
	PCMPGTB X11, X12
	MOVOU cUhi<>+0(SB), X13
	PCMPGTB X0, X13
	PAND X13, X12
	MOVO X0, X8
	MOVOU cLlo<>+0(SB), X11
	PCMPGTB X11, X8
	MOVOU cLhi<>+0(SB), X13
	PCMPGTB X0, X13
	PAND X13, X8
	MOVO X10, X14
	POR X12, X14
	POR X8, X14
	MOVO X14, X11
	PXOR X15, X11
	POR X11, X9
	MOVO X0, X11
	MOVOU subD<>+0(SB), X14
	PSUBB X14, X11
	PAND X10, X11
	MOVO X0, X14
	MOVOU subU<>+0(SB), X13
	PSUBB X13, X14
	PAND X12, X14
	POR X14, X11
	MOVO X0, X14
	MOVOU subL<>+0(SB), X13
	PSUBB X13, X14
	PAND X8, X14
	POR X14, X11
	MOVO X11, X0
	MOVO X1, X10
	MOVOU c0lo<>+0(SB), X11
	PCMPGTB X11, X10
	MOVOU c9hi<>+0(SB), X12
	PCMPGTB X1, X12
	PAND X12, X10
	MOVO X1, X12
	MOVOU cUlo<>+0(SB), X11
	PCMPGTB X11, X12
	MOVOU cUhi<>+0(SB), X13
	PCMPGTB X1, X13
	PAND X13, X12
	MOVO X1, X8
	MOVOU cLlo<>+0(SB), X11
	PCMPGTB X11, X8
	MOVOU cLhi<>+0(SB), X13
	PCMPGTB X1, X13
	PAND X13, X8
	MOVO X10, X14
	POR X12, X14
	POR X8, X14
	MOVO X14, X11
	PXOR X15, X11
	POR X11, X9
	MOVO X1, X11
	MOVOU subD<>+0(SB), X14
	PSUBB X14, X11
	PAND X10, X11
	MOVO X1, X14
	MOVOU subU<>+0(SB), X13
	PSUBB X13, X14
	PAND X12, X14
	POR X14, X11
	MOVO X1, X14
	MOVOU subL<>+0(SB), X13
	PSUBB X13, X14
	PAND X8, X14
	POR X14, X11
	MOVO X11, X1
	PMOVMSKB X9, AX
	TESTL AX, AX
	JNZ sret
	MOVOU madd<>+0(SB), X14
	PMADDUBSW X14, X0
	MOVOU madd<>+0(SB), X14
	PMADDUBSW X14, X1
	PACKUSWB X1, X0
	MOVOU X0, (DI)
	ADDQ $32, SI
	ADDQ $16, DI
	INCQ BX
	CMPQ BX, CX
	JNE sloop
sret:
	MOVQ BX, ret+56(FP)
	RET

TEXT ·decodeBlocksAVX2(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	XORQ BX, BX
	TESTQ CX, CX
	JZ vret
	VPCMPEQB Y15, Y15, Y15
vloop:
	VMOVDQU (SI), Y0
	VMOVDQU 32(SI), Y1
	VPXOR Y9, Y9, Y9
	VMOVDQU v0lo<>+0(SB), Y11
	VPCMPGTB Y11, Y0, Y10
	VMOVDQU v9hi<>+0(SB), Y12
	VPCMPGTB Y0, Y12, Y12
	VPAND Y12, Y10, Y10
	VMOVDQU vUlo<>+0(SB), Y11
	VPCMPGTB Y11, Y0, Y12
	VMOVDQU vUhi<>+0(SB), Y13
	VPCMPGTB Y0, Y13, Y13
	VPAND Y13, Y12, Y12
	VMOVDQU vLlo<>+0(SB), Y11
	VPCMPGTB Y11, Y0, Y8
	VMOVDQU vLhi<>+0(SB), Y13
	VPCMPGTB Y0, Y13, Y13
	VPAND Y13, Y8, Y8
	VPOR Y12, Y10, Y14
	VPOR Y8, Y14, Y14
	VPXOR Y15, Y14, Y11
	VPOR Y11, Y9, Y9
	VMOVDQU vsubD<>+0(SB), Y14
	VPSUBB Y14, Y0, Y11
	VPAND Y10, Y11, Y11
	VMOVDQU vsubU<>+0(SB), Y14
	VPSUBB Y14, Y0, Y13
	VPAND Y12, Y13, Y13
	VPOR Y13, Y11, Y11
	VMOVDQU vsubL<>+0(SB), Y14
	VPSUBB Y14, Y0, Y13
	VPAND Y8, Y13, Y13
	VPOR Y13, Y11, Y11
	VMOVDQA Y11, Y0
	VMOVDQU v0lo<>+0(SB), Y11
	VPCMPGTB Y11, Y1, Y10
	VMOVDQU v9hi<>+0(SB), Y12
	VPCMPGTB Y1, Y12, Y12
	VPAND Y12, Y10, Y10
	VMOVDQU vUlo<>+0(SB), Y11
	VPCMPGTB Y11, Y1, Y12
	VMOVDQU vUhi<>+0(SB), Y13
	VPCMPGTB Y1, Y13, Y13
	VPAND Y13, Y12, Y12
	VMOVDQU vLlo<>+0(SB), Y11
	VPCMPGTB Y11, Y1, Y8
	VMOVDQU vLhi<>+0(SB), Y13
	VPCMPGTB Y1, Y13, Y13
	VPAND Y13, Y8, Y8
	VPOR Y12, Y10, Y14
	VPOR Y8, Y14, Y14
	VPXOR Y15, Y14, Y11
	VPOR Y11, Y9, Y9
	VMOVDQU vsubD<>+0(SB), Y14
	VPSUBB Y14, Y1, Y11
	VPAND Y10, Y11, Y11
	VMOVDQU vsubU<>+0(SB), Y14
	VPSUBB Y14, Y1, Y13
	VPAND Y12, Y13, Y13
	VPOR Y13, Y11, Y11
	VMOVDQU vsubL<>+0(SB), Y14
	VPSUBB Y14, Y1, Y13
	VPAND Y8, Y13, Y13
	VPOR Y13, Y11, Y11
	VMOVDQA Y11, Y1
	VPMOVMSKB Y9, AX
	TESTL AX, AX
	JNZ vret
	VMOVDQU vmadd<>+0(SB), Y14
	VPMADDUBSW Y0, Y14, Y0
	VPMADDUBSW Y1, Y14, Y1
	VPACKUSWB Y1, Y0, Y0
	VPERMQ $0xD8, Y0, Y0
	VMOVDQU Y0, (DI)
	ADDQ $64, SI
	ADDQ $32, DI
	INCQ BX
	CMPQ BX, CX
	JNE vloop
vret:
	VZEROUPPER
	MOVQ BX, ret+56(FP)
	RET

DATA c0lo<>+0(SB)/1, $0x2f
DATA c0lo<>+1(SB)/1, $0x2f
DATA c0lo<>+2(SB)/1, $0x2f
DATA c0lo<>+3(SB)/1, $0x2f
DATA c0lo<>+4(SB)/1, $0x2f
DATA c0lo<>+5(SB)/1, $0x2f
DATA c0lo<>+6(SB)/1, $0x2f
DATA c0lo<>+7(SB)/1, $0x2f
DATA c0lo<>+8(SB)/1, $0x2f
DATA c0lo<>+9(SB)/1, $0x2f
DATA c0lo<>+10(SB)/1, $0x2f
DATA c0lo<>+11(SB)/1, $0x2f
DATA c0lo<>+12(SB)/1, $0x2f
DATA c0lo<>+13(SB)/1, $0x2f
DATA c0lo<>+14(SB)/1, $0x2f
DATA c0lo<>+15(SB)/1, $0x2f
GLOBL c0lo<>(SB), RODATA|NOPTR, $16

DATA c9hi<>+0(SB)/1, $0x3a
DATA c9hi<>+1(SB)/1, $0x3a
DATA c9hi<>+2(SB)/1, $0x3a
DATA c9hi<>+3(SB)/1, $0x3a
DATA c9hi<>+4(SB)/1, $0x3a
DATA c9hi<>+5(SB)/1, $0x3a
DATA c9hi<>+6(SB)/1, $0x3a
DATA c9hi<>+7(SB)/1, $0x3a
DATA c9hi<>+8(SB)/1, $0x3a
DATA c9hi<>+9(SB)/1, $0x3a
DATA c9hi<>+10(SB)/1, $0x3a
DATA c9hi<>+11(SB)/1, $0x3a
DATA c9hi<>+12(SB)/1, $0x3a
DATA c9hi<>+13(SB)/1, $0x3a
DATA c9hi<>+14(SB)/1, $0x3a
DATA c9hi<>+15(SB)/1, $0x3a
GLOBL c9hi<>(SB), RODATA|NOPTR, $16

DATA cUlo<>+0(SB)/1, $0x40
DATA cUlo<>+1(SB)/1, $0x40
DATA cUlo<>+2(SB)/1, $0x40
DATA cUlo<>+3(SB)/1, $0x40
DATA cUlo<>+4(SB)/1, $0x40
DATA cUlo<>+5(SB)/1, $0x40
DATA cUlo<>+6(SB)/1, $0x40
DATA cUlo<>+7(SB)/1, $0x40
DATA cUlo<>+8(SB)/1, $0x40
DATA cUlo<>+9(SB)/1, $0x40
DATA cUlo<>+10(SB)/1, $0x40
DATA cUlo<>+11(SB)/1, $0x40
DATA cUlo<>+12(SB)/1, $0x40
DATA cUlo<>+13(SB)/1, $0x40
DATA cUlo<>+14(SB)/1, $0x40
DATA cUlo<>+15(SB)/1, $0x40
GLOBL cUlo<>(SB), RODATA|NOPTR, $16

DATA cUhi<>+0(SB)/1, $0x47
DATA cUhi<>+1(SB)/1, $0x47
DATA cUhi<>+2(SB)/1, $0x47
DATA cUhi<>+3(SB)/1, $0x47
DATA cUhi<>+4(SB)/1, $0x47
DATA cUhi<>+5(SB)/1, $0x47
DATA cUhi<>+6(SB)/1, $0x47
DATA cUhi<>+7(SB)/1, $0x47
DATA cUhi<>+8(SB)/1, $0x47
DATA cUhi<>+9(SB)/1, $0x47
DATA cUhi<>+10(SB)/1, $0x47
DATA cUhi<>+11(SB)/1, $0x47
DATA cUhi<>+12(SB)/1, $0x47
DATA cUhi<>+13(SB)/1, $0x47
DATA cUhi<>+14(SB)/1, $0x47
DATA cUhi<>+15(SB)/1, $0x47
GLOBL cUhi<>(SB), RODATA|NOPTR, $16

DATA cLlo<>+0(SB)/1, $0x60
DATA cLlo<>+1(SB)/1, $0x60
DATA cLlo<>+2(SB)/1, $0x60
DATA cLlo<>+3(SB)/1, $0x60
DATA cLlo<>+4(SB)/1, $0x60
DATA cLlo<>+5(SB)/1, $0x60
DATA cLlo<>+6(SB)/1, $0x60
DATA cLlo<>+7(SB)/1, $0x60
DATA cLlo<>+8(SB)/1, $0x60
DATA cLlo<>+9(SB)/1, $0x60
DATA cLlo<>+10(SB)/1, $0x60
DATA cLlo<>+11(SB)/1, $0x60
DATA cLlo<>+12(SB)/1, $0x60
DATA cLlo<>+13(SB)/1, $0x60
DATA cLlo<>+14(SB)/1, $0x60
DATA cLlo<>+15(SB)/1, $0x60
GLOBL cLlo<>(SB), RODATA|NOPTR, $16

DATA cLhi<>+0(SB)/1, $0x67
DATA cLhi<>+1(SB)/1, $0x67
DATA cLhi<>+2(SB)/1, $0x67
DATA cLhi<>+3(SB)/1, $0x67
DATA cLhi<>+4(SB)/1, $0x67
DATA cLhi<>+5(SB)/1, $0x67
DATA cLhi<>+6(SB)/1, $0x67
DATA cLhi<>+7(SB)/1, $0x67
DATA cLhi<>+8(SB)/1, $0x67
DATA cLhi<>+9(SB)/1, $0x67
DATA cLhi<>+10(SB)/1, $0x67
DATA cLhi<>+11(SB)/1, $0x67
DATA cLhi<>+12(SB)/1, $0x67
DATA cLhi<>+13(SB)/1, $0x67
DATA cLhi<>+14(SB)/1, $0x67
DATA cLhi<>+15(SB)/1, $0x67
GLOBL cLhi<>(SB), RODATA|NOPTR, $16

DATA subD<>+0(SB)/1, $0x30
DATA subD<>+1(SB)/1, $0x30
DATA subD<>+2(SB)/1, $0x30
DATA subD<>+3(SB)/1, $0x30
DATA subD<>+4(SB)/1, $0x30
DATA subD<>+5(SB)/1, $0x30
DATA subD<>+6(SB)/1, $0x30
DATA subD<>+7(SB)/1, $0x30
DATA subD<>+8(SB)/1, $0x30
DATA subD<>+9(SB)/1, $0x30
DATA subD<>+10(SB)/1, $0x30
DATA subD<>+11(SB)/1, $0x30
DATA subD<>+12(SB)/1, $0x30
DATA subD<>+13(SB)/1, $0x30
DATA subD<>+14(SB)/1, $0x30
DATA subD<>+15(SB)/1, $0x30
GLOBL subD<>(SB), RODATA|NOPTR, $16

DATA subU<>+0(SB)/1, $0x37
DATA subU<>+1(SB)/1, $0x37
DATA subU<>+2(SB)/1, $0x37
DATA subU<>+3(SB)/1, $0x37
DATA subU<>+4(SB)/1, $0x37
DATA subU<>+5(SB)/1, $0x37
DATA subU<>+6(SB)/1, $0x37
DATA subU<>+7(SB)/1, $0x37
DATA subU<>+8(SB)/1, $0x37
DATA subU<>+9(SB)/1, $0x37
DATA subU<>+10(SB)/1, $0x37
DATA subU<>+11(SB)/1, $0x37
DATA subU<>+12(SB)/1, $0x37
DATA subU<>+13(SB)/1, $0x37
DATA subU<>+14(SB)/1, $0x37
DATA subU<>+15(SB)/1, $0x37
GLOBL subU<>(SB), RODATA|NOPTR, $16

DATA subL<>+0(SB)/1, $0x57
DATA subL<>+1(SB)/1, $0x57
DATA subL<>+2(SB)/1, $0x57
DATA subL<>+3(SB)/1, $0x57
DATA subL<>+4(SB)/1, $0x57
DATA subL<>+5(SB)/1, $0x57
DATA subL<>+6(SB)/1, $0x57
DATA subL<>+7(SB)/1, $0x57
DATA subL<>+8(SB)/1, $0x57
DATA subL<>+9(SB)/1, $0x57
DATA subL<>+10(SB)/1, $0x57
DATA subL<>+11(SB)/1, $0x57
DATA subL<>+12(SB)/1, $0x57
DATA subL<>+13(SB)/1, $0x57
DATA subL<>+14(SB)/1, $0x57
DATA subL<>+15(SB)/1, $0x57
GLOBL subL<>(SB), RODATA|NOPTR, $16

DATA madd<>+0(SB)/1, $0x10
DATA madd<>+1(SB)/1, $0x01
DATA madd<>+2(SB)/1, $0x10
DATA madd<>+3(SB)/1, $0x01
DATA madd<>+4(SB)/1, $0x10
DATA madd<>+5(SB)/1, $0x01
DATA madd<>+6(SB)/1, $0x10
DATA madd<>+7(SB)/1, $0x01
DATA madd<>+8(SB)/1, $0x10
DATA madd<>+9(SB)/1, $0x01
DATA madd<>+10(SB)/1, $0x10
DATA madd<>+11(SB)/1, $0x01
DATA madd<>+12(SB)/1, $0x10
DATA madd<>+13(SB)/1, $0x01
DATA madd<>+14(SB)/1, $0x10
DATA madd<>+15(SB)/1, $0x01
GLOBL madd<>(SB), RODATA|NOPTR, $16

DATA v0lo<>+0(SB)/1, $0x2f
DATA v0lo<>+1(SB)/1, $0x2f
DATA v0lo<>+2(SB)/1, $0x2f
DATA v0lo<>+3(SB)/1, $0x2f
DATA v0lo<>+4(SB)/1, $0x2f
DATA v0lo<>+5(SB)/1, $0x2f
DATA v0lo<>+6(SB)/1, $0x2f
DATA v0lo<>+7(SB)/1, $0x2f
DATA v0lo<>+8(SB)/1, $0x2f
DATA v0lo<>+9(SB)/1, $0x2f
DATA v0lo<>+10(SB)/1, $0x2f
DATA v0lo<>+11(SB)/1, $0x2f
DATA v0lo<>+12(SB)/1, $0x2f
DATA v0lo<>+13(SB)/1, $0x2f
DATA v0lo<>+14(SB)/1, $0x2f
DATA v0lo<>+15(SB)/1, $0x2f
DATA v0lo<>+16(SB)/1, $0x2f
DATA v0lo<>+17(SB)/1, $0x2f
DATA v0lo<>+18(SB)/1, $0x2f
DATA v0lo<>+19(SB)/1, $0x2f
DATA v0lo<>+20(SB)/1, $0x2f
DATA v0lo<>+21(SB)/1, $0x2f
DATA v0lo<>+22(SB)/1, $0x2f
DATA v0lo<>+23(SB)/1, $0x2f
DATA v0lo<>+24(SB)/1, $0x2f
DATA v0lo<>+25(SB)/1, $0x2f
DATA v0lo<>+26(SB)/1, $0x2f
DATA v0lo<>+27(SB)/1, $0x2f
DATA v0lo<>+28(SB)/1, $0x2f
DATA v0lo<>+29(SB)/1, $0x2f
DATA v0lo<>+30(SB)/1, $0x2f
DATA v0lo<>+31(SB)/1, $0x2f
GLOBL v0lo<>(SB), RODATA|NOPTR, $32

DATA v9hi<>+0(SB)/1, $0x3a
DATA v9hi<>+1(SB)/1, $0x3a
DATA v9hi<>+2(SB)/1, $0x3a
DATA v9hi<>+3(SB)/1, $0x3a
DATA v9hi<>+4(SB)/1, $0x3a
DATA v9hi<>+5(SB)/1, $0x3a
DATA v9hi<>+6(SB)/1, $0x3a
DATA v9hi<>+7(SB)/1, $0x3a
DATA v9hi<>+8(SB)/1, $0x3a
DATA v9hi<>+9(SB)/1, $0x3a
DATA v9hi<>+10(SB)/1, $0x3a
DATA v9hi<>+11(SB)/1, $0x3a
DATA v9hi<>+12(SB)/1, $0x3a
DATA v9hi<>+13(SB)/1, $0x3a
DATA v9hi<>+14(SB)/1, $0x3a
DATA v9hi<>+15(SB)/1, $0x3a
DATA v9hi<>+16(SB)/1, $0x3a
DATA v9hi<>+17(SB)/1, $0x3a
DATA v9hi<>+18(SB)/1, $0x3a
DATA v9hi<>+19(SB)/1, $0x3a
DATA v9hi<>+20(SB)/1, $0x3a
DATA v9hi<>+21(SB)/1, $0x3a
DATA v9hi<>+22(SB)/1, $0x3a
DATA v9hi<>+23(SB)/1, $0x3a
DATA v9hi<>+24(SB)/1, $0x3a
DATA v9hi<>+25(SB)/1, $0x3a
DATA v9hi<>+26(SB)/1, $0x3a
DATA v9hi<>+27(SB)/1, $0x3a
DATA v9hi<>+28(SB)/1, $0x3a
DATA v9hi<>+29(SB)/1, $0x3a
DATA v9hi<>+30(SB)/1, $0x3a
DATA v9hi<>+31(SB)/1, $0x3a
GLOBL v9hi<>(SB), RODATA|NOPTR, $32

DATA vUlo<>+0(SB)/1, $0x40
DATA vUlo<>+1(SB)/1, $0x40
DATA vUlo<>+2(SB)/1, $0x40
DATA vUlo<>+3(SB)/1, $0x40
DATA vUlo<>+4(SB)/1, $0x40
DATA vUlo<>+5(SB)/1, $0x40
DATA vUlo<>+6(SB)/1, $0x40
DATA vUlo<>+7(SB)/1, $0x40
DATA vUlo<>+8(SB)/1, $0x40
DATA vUlo<>+9(SB)/1, $0x40
DATA vUlo<>+10(SB)/1, $0x40
DATA vUlo<>+11(SB)/1, $0x40
DATA vUlo<>+12(SB)/1, $0x40
DATA vUlo<>+13(SB)/1, $0x40
DATA vUlo<>+14(SB)/1, $0x40
DATA vUlo<>+15(SB)/1, $0x40
DATA vUlo<>+16(SB)/1, $0x40
DATA vUlo<>+17(SB)/1, $0x40
DATA vUlo<>+18(SB)/1, $0x40
DATA vUlo<>+19(SB)/1, $0x40
DATA vUlo<>+20(SB)/1, $0x40
DATA vUlo<>+21(SB)/1, $0x40
DATA vUlo<>+22(SB)/1, $0x40
DATA vUlo<>+23(SB)/1, $0x40
DATA vUlo<>+24(SB)/1, $0x40
DATA vUlo<>+25(SB)/1, $0x40
DATA vUlo<>+26(SB)/1, $0x40
DATA vUlo<>+27(SB)/1, $0x40
DATA vUlo<>+28(SB)/1, $0x40
DATA vUlo<>+29(SB)/1, $0x40
DATA vUlo<>+30(SB)/1, $0x40
DATA vUlo<>+31(SB)/1, $0x40
GLOBL vUlo<>(SB), RODATA|NOPTR, $32

DATA vUhi<>+0(SB)/1, $0x47
DATA vUhi<>+1(SB)/1, $0x47
DATA vUhi<>+2(SB)/1, $0x47
DATA vUhi<>+3(SB)/1, $0x47
DATA vUhi<>+4(SB)/1, $0x47
DATA vUhi<>+5(SB)/1, $0x47
DATA vUhi<>+6(SB)/1, $0x47
DATA vUhi<>+7(SB)/1, $0x47
DATA vUhi<>+8(SB)/1, $0x47
DATA vUhi<>+9(SB)/1, $0x47
DATA vUhi<>+10(SB)/1, $0x47
DATA vUhi<>+11(SB)/1, $0x47
DATA vUhi<>+12(SB)/1, $0x47
DATA vUhi<>+13(SB)/1, $0x47
DATA vUhi<>+14(SB)/1, $0x47
DATA vUhi<>+15(SB)/1, $0x47
DATA vUhi<>+16(SB)/1, $0x47
DATA vUhi<>+17(SB)/1, $0x47
DATA vUhi<>+18(SB)/1, $0x47
DATA vUhi<>+19(SB)/1, $0x47
DATA vUhi<>+20(SB)/1, $0x47
DATA vUhi<>+21(SB)/1, $0x47
DATA vUhi<>+22(SB)/1, $0x47
DATA vUhi<>+23(SB)/1, $0x47
DATA vUhi<>+24(SB)/1, $0x47
DATA vUhi<>+25(SB)/1, $0x47
DATA vUhi<>+26(SB)/1, $0x47
DATA vUhi<>+27(SB)/1, $0x47
DATA vUhi<>+28(SB)/1, $0x47
DATA vUhi<>+29(SB)/1, $0x47
DATA vUhi<>+30(SB)/1, $0x47
DATA vUhi<>+31(SB)/1, $0x47
GLOBL vUhi<>(SB), RODATA|NOPTR, $32

DATA vLlo<>+0(SB)/1, $0x60
DATA vLlo<>+1(SB)/1, $0x60
DATA vLlo<>+2(SB)/1, $0x60
DATA vLlo<>+3(SB)/1, $0x60
DATA vLlo<>+4(SB)/1, $0x60
DATA vLlo<>+5(SB)/1, $0x60
DATA vLlo<>+6(SB)/1, $0x60
DATA vLlo<>+7(SB)/1, $0x60
DATA vLlo<>+8(SB)/1, $0x60
DATA vLlo<>+9(SB)/1, $0x60
DATA vLlo<>+10(SB)/1, $0x60
DATA vLlo<>+11(SB)/1, $0x60
DATA vLlo<>+12(SB)/1, $0x60
DATA vLlo<>+13(SB)/1, $0x60
DATA vLlo<>+14(SB)/1, $0x60
DATA vLlo<>+15(SB)/1, $0x60
DATA vLlo<>+16(SB)/1, $0x60
DATA vLlo<>+17(SB)/1, $0x60
DATA vLlo<>+18(SB)/1, $0x60
DATA vLlo<>+19(SB)/1, $0x60
DATA vLlo<>+20(SB)/1, $0x60
DATA vLlo<>+21(SB)/1, $0x60
DATA vLlo<>+22(SB)/1, $0x60
DATA vLlo<>+23(SB)/1, $0x60
DATA vLlo<>+24(SB)/1, $0x60
DATA vLlo<>+25(SB)/1, $0x60
DATA vLlo<>+26(SB)/1, $0x60
DATA vLlo<>+27(SB)/1, $0x60
DATA vLlo<>+28(SB)/1, $0x60
DATA vLlo<>+29(SB)/1, $0x60
DATA vLlo<>+30(SB)/1, $0x60
DATA vLlo<>+31(SB)/1, $0x60
GLOBL vLlo<>(SB), RODATA|NOPTR, $32

DATA vLhi<>+0(SB)/1, $0x67
DATA vLhi<>+1(SB)/1, $0x67
DATA vLhi<>+2(SB)/1, $0x67
DATA vLhi<>+3(SB)/1, $0x67
DATA vLhi<>+4(SB)/1, $0x67
DATA vLhi<>+5(SB)/1, $0x67
DATA vLhi<>+6(SB)/1, $0x67
DATA vLhi<>+7(SB)/1, $0x67
DATA vLhi<>+8(SB)/1, $0x67
DATA vLhi<>+9(SB)/1, $0x67
DATA vLhi<>+10(SB)/1, $0x67
DATA vLhi<>+11(SB)/1, $0x67
DATA vLhi<>+12(SB)/1, $0x67
DATA vLhi<>+13(SB)/1, $0x67
DATA vLhi<>+14(SB)/1, $0x67
DATA vLhi<>+15(SB)/1, $0x67
DATA vLhi<>+16(SB)/1, $0x67
DATA vLhi<>+17(SB)/1, $0x67
DATA vLhi<>+18(SB)/1, $0x67
DATA vLhi<>+19(SB)/1, $0x67
DATA vLhi<>+20(SB)/1, $0x67
DATA vLhi<>+21(SB)/1, $0x67
DATA vLhi<>+22(SB)/1, $0x67
DATA vLhi<>+23(SB)/1, $0x67
DATA vLhi<>+24(SB)/1, $0x67
DATA vLhi<>+25(SB)/1, $0x67
DATA vLhi<>+26(SB)/1, $0x67
DATA vLhi<>+27(SB)/1, $0x67
DATA vLhi<>+28(SB)/1, $0x67
DATA vLhi<>+29(SB)/1, $0x67
DATA vLhi<>+30(SB)/1, $0x67
DATA vLhi<>+31(SB)/1, $0x67
GLOBL vLhi<>(SB), RODATA|NOPTR, $32

DATA vsubD<>+0(SB)/1, $0x30
DATA vsubD<>+1(SB)/1, $0x30
DATA vsubD<>+2(SB)/1, $0x30
DATA vsubD<>+3(SB)/1, $0x30
DATA vsubD<>+4(SB)/1, $0x30
DATA vsubD<>+5(SB)/1, $0x30
DATA vsubD<>+6(SB)/1, $0x30
DATA vsubD<>+7(SB)/1, $0x30
DATA vsubD<>+8(SB)/1, $0x30
DATA vsubD<>+9(SB)/1, $0x30
DATA vsubD<>+10(SB)/1, $0x30
DATA vsubD<>+11(SB)/1, $0x30
DATA vsubD<>+12(SB)/1, $0x30
DATA vsubD<>+13(SB)/1, $0x30
DATA vsubD<>+14(SB)/1, $0x30
DATA vsubD<>+15(SB)/1, $0x30
DATA vsubD<>+16(SB)/1, $0x30
DATA vsubD<>+17(SB)/1, $0x30
DATA vsubD<>+18(SB)/1, $0x30
DATA vsubD<>+19(SB)/1, $0x30
DATA vsubD<>+20(SB)/1, $0x30
DATA vsubD<>+21(SB)/1, $0x30
DATA vsubD<>+22(SB)/1, $0x30
DATA vsubD<>+23(SB)/1, $0x30
DATA vsubD<>+24(SB)/1, $0x30
DATA vsubD<>+25(SB)/1, $0x30
DATA vsubD<>+26(SB)/1, $0x30
DATA vsubD<>+27(SB)/1, $0x30
DATA vsubD<>+28(SB)/1, $0x30
DATA vsubD<>+29(SB)/1, $0x30
DATA vsubD<>+30(SB)/1, $0x30
DATA vsubD<>+31(SB)/1, $0x30
GLOBL vsubD<>(SB), RODATA|NOPTR, $32

DATA vsubU<>+0(SB)/1, $0x37
DATA vsubU<>+1(SB)/1, $0x37
DATA vsubU<>+2(SB)/1, $0x37
DATA vsubU<>+3(SB)/1, $0x37
DATA vsubU<>+4(SB)/1, $0x37
DATA vsubU<>+5(SB)/1, $0x37
DATA vsubU<>+6(SB)/1, $0x37
DATA vsubU<>+7(SB)/1, $0x37
DATA vsubU<>+8(SB)/1, $0x37
DATA vsubU<>+9(SB)/1, $0x37
DATA vsubU<>+10(SB)/1, $0x37
DATA vsubU<>+11(SB)/1, $0x37
DATA vsubU<>+12(SB)/1, $0x37
DATA vsubU<>+13(SB)/1, $0x37
DATA vsubU<>+14(SB)/1, $0x37
DATA vsubU<>+15(SB)/1, $0x37
DATA vsubU<>+16(SB)/1, $0x37
DATA vsubU<>+17(SB)/1, $0x37
DATA vsubU<>+18(SB)/1, $0x37
DATA vsubU<>+19(SB)/1, $0x37
DATA vsubU<>+20(SB)/1, $0x37
DATA vsubU<>+21(SB)/1, $0x37
DATA vsubU<>+22(SB)/1, $0x37
DATA vsubU<>+23(SB)/1, $0x37
DATA vsubU<>+24(SB)/1, $0x37
DATA vsubU<>+25(SB)/1, $0x37
DATA vsubU<>+26(SB)/1, $0x37
DATA vsubU<>+27(SB)/1, $0x37
DATA vsubU<>+28(SB)/1, $0x37
DATA vsubU<>+29(SB)/1, $0x37
DATA vsubU<>+30(SB)/1, $0x37
DATA vsubU<>+31(SB)/1, $0x37
GLOBL vsubU<>(SB), RODATA|NOPTR, $32

DATA vsubL<>+0(SB)/1, $0x57
DATA vsubL<>+1(SB)/1, $0x57
DATA vsubL<>+2(SB)/1, $0x57
DATA vsubL<>+3(SB)/1, $0x57
DATA vsubL<>+4(SB)/1, $0x57
DATA vsubL<>+5(SB)/1, $0x57
DATA vsubL<>+6(SB)/1, $0x57
DATA vsubL<>+7(SB)/1, $0x57
DATA vsubL<>+8(SB)/1, $0x57
DATA vsubL<>+9(SB)/1, $0x57
DATA vsubL<>+10(SB)/1, $0x57
DATA vsubL<>+11(SB)/1, $0x57
DATA vsubL<>+12(SB)/1, $0x57
DATA vsubL<>+13(SB)/1, $0x57
DATA vsubL<>+14(SB)/1, $0x57
DATA vsubL<>+15(SB)/1, $0x57
DATA vsubL<>+16(SB)/1, $0x57
DATA vsubL<>+17(SB)/1, $0x57
DATA vsubL<>+18(SB)/1, $0x57
DATA vsubL<>+19(SB)/1, $0x57
DATA vsubL<>+20(SB)/1, $0x57
DATA vsubL<>+21(SB)/1, $0x57
DATA vsubL<>+22(SB)/1, $0x57
DATA vsubL<>+23(SB)/1, $0x57
DATA vsubL<>+24(SB)/1, $0x57
DATA vsubL<>+25(SB)/1, $0x57
DATA vsubL<>+26(SB)/1, $0x57
DATA vsubL<>+27(SB)/1, $0x57
DATA vsubL<>+28(SB)/1, $0x57
DATA vsubL<>+29(SB)/1, $0x57
DATA vsubL<>+30(SB)/1, $0x57
DATA vsubL<>+31(SB)/1, $0x57
GLOBL vsubL<>(SB), RODATA|NOPTR, $32

DATA vmadd<>+0(SB)/1, $0x10
DATA vmadd<>+1(SB)/1, $0x01
DATA vmadd<>+2(SB)/1, $0x10
DATA vmadd<>+3(SB)/1, $0x01
DATA vmadd<>+4(SB)/1, $0x10
DATA vmadd<>+5(SB)/1, $0x01
DATA vmadd<>+6(SB)/1, $0x10
DATA vmadd<>+7(SB)/1, $0x01
DATA vmadd<>+8(SB)/1, $0x10
DATA vmadd<>+9(SB)/1, $0x01
DATA vmadd<>+10(SB)/1, $0x10
DATA vmadd<>+11(SB)/1, $0x01
DATA vmadd<>+12(SB)/1, $0x10
DATA vmadd<>+13(SB)/1, $0x01
DATA vmadd<>+14(SB)/1, $0x10
DATA vmadd<>+15(SB)/1, $0x01
DATA vmadd<>+16(SB)/1, $0x10
DATA vmadd<>+17(SB)/1, $0x01
DATA vmadd<>+18(SB)/1, $0x10
DATA vmadd<>+19(SB)/1, $0x01
DATA vmadd<>+20(SB)/1, $0x10
DATA vmadd<>+21(SB)/1, $0x01
DATA vmadd<>+22(SB)/1, $0x10
DATA vmadd<>+23(SB)/1, $0x01
DATA vmadd<>+24(SB)/1, $0x10
DATA vmadd<>+25(SB)/1, $0x01
DATA vmadd<>+26(SB)/1, $0x10
DATA vmadd<>+27(SB)/1, $0x01
DATA vmadd<>+28(SB)/1, $0x10
DATA vmadd<>+29(SB)/1, $0x01
DATA vmadd<>+30(SB)/1, $0x10
DATA vmadd<>+31(SB)/1, $0x01
GLOBL vmadd<>(SB), RODATA|NOPTR, $32

