//go:build s390x

package hex

// decodeBlocksVX decodes whole 32-char source blocks into 16 bytes each, using
// the s390x vector-facility kernel generated by go-asmgen (decode_s390x_gen.go),
// in decode_s390x.s. It attempts n blocks and returns the number fully decoded
// before the first block containing an invalid char (== n when every attempted
// block is valid); the caller resumes a scalar encoding/hex-style loop from there
// so the error offset is bit-exact.
func decodeBlocksVX(dst, src []byte, n int) int

// decodeSIMD decodes whole 32-char blocks of src into dst with the vector kernel,
// returning the bytes written to dst and consumed from src. It stops at the first
// block containing an invalid char (so the caller's scalar tail produces the
// exact InvalidByteError offset) and never reads or writes a partial block.
func decodeSIMD(dst, src []byte) (dstDone, srcDone int) {
	if len(src) >= 32 {
		blocks := len(src) / 32
		done := decodeBlocksVX(dst, src, blocks)
		return done * 16, done * 32
	}
	return 0, 0
}
