//go:build arm64

package hex

// decodeBlocks decodes up to n blocks of 32 hex chars into 16 bytes each via
// NEON: a VLD2 deinterleaving load separates the hi/lo-nibble chars into two
// planes, each plane is range-validated and mapped to its 0..15 nibble, and the
// two planes are fused with (hi<<4)|lo. It returns the number of blocks fully
// decoded before the first block containing an invalid char (== n when every
// attempted block is valid); the caller resumes a scalar encoding/hex-style loop
// from there so the error offset is bit-exact. Generated by go-asmgen
// (decode_arm64_gen.go), in decode_arm64.s.
func decodeBlocks(dst, src []byte, n int) int

// decodeSIMD decodes whole 32-char blocks of src into dst, returning the bytes
// written to dst and consumed from src. It stops at the first block containing
// an invalid char (so the caller's scalar tail produces the exact
// InvalidByteError offset) and never reads or writes a partial trailing block.
func decodeSIMD(dst, src []byte) (dstDone, srcDone int) {
	if len(src) < 32 {
		return 0, 0
	}
	blocks := len(src) / 32
	done := decodeBlocks(dst, src, blocks)
	return done * 16, done * 32
}
