// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·decodeBlocksVSX(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $0, R7
	CMP R5, $0
	BEQ dret
	MOVD $0, R8
	MOVD $0, R9
	MOVD $d_c0lo<>+0(SB), R10
	LXVB16X (R0)(R10), VS40
	MOVD $d_c9hi<>+0(SB), R10
	LXVB16X (R0)(R10), VS41
	MOVD $d_cUlo<>+0(SB), R10
	LXVB16X (R0)(R10), VS42
	MOVD $d_cUhi<>+0(SB), R10
	LXVB16X (R0)(R10), VS43
	MOVD $d_cLlo<>+0(SB), R10
	LXVB16X (R0)(R10), VS44
	MOVD $d_cLhi<>+0(SB), R10
	LXVB16X (R0)(R10), VS45
	MOVD $d_subD<>+0(SB), R10
	LXVB16X (R0)(R10), VS46
	MOVD $d_subU<>+0(SB), R10
	LXVB16X (R0)(R10), VS47
	MOVD $d_subL<>+0(SB), R10
	LXVB16X (R0)(R10), VS48
	MOVD $d_four<>+0(SB), R10
	LXVB16X (R0)(R10), VS49
	MOVD $d_gHi<>+0(SB), R10
	LXVB16X (R0)(R10), VS50
	MOVD $d_gLo<>+0(SB), R10
	LXVB16X (R0)(R10), VS51
dloop:
	LXVB16X (R8)(R4), VS32
	ADD $16, R8
	LXVB16X (R8)(R4), VS33
	ADD $-16, R8
	VXOR V20, V20, V20
	VCMPGTUB V0, V8, V21
	VCMPGTUB V9, V0, V22
	VAND V21, V22, V21
	VCMPGTUB V0, V10, V22
	VCMPGTUB V11, V0, V23
	VAND V22, V23, V22
	VCMPGTUB V0, V12, V23
	VCMPGTUB V13, V0, V24
	VAND V23, V24, V23
	VOR V21, V22, V24
	VOR V24, V23, V24
	VNOR V24, V24, V25
	VOR V20, V25, V20
	VSUBUBM V0, V14, V26
	VAND V26, V21, V26
	VSUBUBM V0, V15, V27
	VAND V27, V22, V27
	VOR V26, V27, V26
	VSUBUBM V0, V16, V27
	VAND V27, V23, V27
	VOR V26, V27, V26
	VOR V26, V26, V0
	VCMPGTUB V1, V8, V21
	VCMPGTUB V9, V1, V22
	VAND V21, V22, V21
	VCMPGTUB V1, V10, V22
	VCMPGTUB V11, V1, V23
	VAND V22, V23, V22
	VCMPGTUB V1, V12, V23
	VCMPGTUB V13, V1, V24
	VAND V23, V24, V23
	VOR V21, V22, V24
	VOR V24, V23, V24
	VNOR V24, V24, V25
	VOR V20, V25, V20
	VSUBUBM V1, V14, V26
	VAND V26, V21, V26
	VSUBUBM V1, V15, V27
	VAND V27, V22, V27
	VOR V26, V27, V26
	VSUBUBM V1, V16, V27
	VAND V27, V23, V27
	VOR V26, V27, V26
	VOR V26, V26, V1
	MFVSRD VS52, R10
	XXPERMDI VS52, VS52, $2, VS60
	MFVSRD VS60, R11
	OR R11, R10, R10
	CMP R10, $0
	BNE dret
	VPERM V0, V1, V18, V21
	VPERM V0, V1, V19, V22
	VSLB V21, V17, V21
	VOR V21, V22, V21
	STXVB16X VS53, (R9)(R3)
	ADD $32, R8
	ADD $16, R9
	ADD $1, R7
	CMP R7, R5
	BNE dloop
dret:
	MOVD R7, ret+56(FP)
	RET

DATA d_c0lo<>+0(SB)/1, $0x2f
DATA d_c0lo<>+1(SB)/1, $0x2f
DATA d_c0lo<>+2(SB)/1, $0x2f
DATA d_c0lo<>+3(SB)/1, $0x2f
DATA d_c0lo<>+4(SB)/1, $0x2f
DATA d_c0lo<>+5(SB)/1, $0x2f
DATA d_c0lo<>+6(SB)/1, $0x2f
DATA d_c0lo<>+7(SB)/1, $0x2f
DATA d_c0lo<>+8(SB)/1, $0x2f
DATA d_c0lo<>+9(SB)/1, $0x2f
DATA d_c0lo<>+10(SB)/1, $0x2f
DATA d_c0lo<>+11(SB)/1, $0x2f
DATA d_c0lo<>+12(SB)/1, $0x2f
DATA d_c0lo<>+13(SB)/1, $0x2f
DATA d_c0lo<>+14(SB)/1, $0x2f
DATA d_c0lo<>+15(SB)/1, $0x2f
GLOBL d_c0lo<>(SB), RODATA|NOPTR, $16

DATA d_c9hi<>+0(SB)/1, $0x3a
DATA d_c9hi<>+1(SB)/1, $0x3a
DATA d_c9hi<>+2(SB)/1, $0x3a
DATA d_c9hi<>+3(SB)/1, $0x3a
DATA d_c9hi<>+4(SB)/1, $0x3a
DATA d_c9hi<>+5(SB)/1, $0x3a
DATA d_c9hi<>+6(SB)/1, $0x3a
DATA d_c9hi<>+7(SB)/1, $0x3a
DATA d_c9hi<>+8(SB)/1, $0x3a
DATA d_c9hi<>+9(SB)/1, $0x3a
DATA d_c9hi<>+10(SB)/1, $0x3a
DATA d_c9hi<>+11(SB)/1, $0x3a
DATA d_c9hi<>+12(SB)/1, $0x3a
DATA d_c9hi<>+13(SB)/1, $0x3a
DATA d_c9hi<>+14(SB)/1, $0x3a
DATA d_c9hi<>+15(SB)/1, $0x3a
GLOBL d_c9hi<>(SB), RODATA|NOPTR, $16

DATA d_cUlo<>+0(SB)/1, $0x40
DATA d_cUlo<>+1(SB)/1, $0x40
DATA d_cUlo<>+2(SB)/1, $0x40
DATA d_cUlo<>+3(SB)/1, $0x40
DATA d_cUlo<>+4(SB)/1, $0x40
DATA d_cUlo<>+5(SB)/1, $0x40
DATA d_cUlo<>+6(SB)/1, $0x40
DATA d_cUlo<>+7(SB)/1, $0x40
DATA d_cUlo<>+8(SB)/1, $0x40
DATA d_cUlo<>+9(SB)/1, $0x40
DATA d_cUlo<>+10(SB)/1, $0x40
DATA d_cUlo<>+11(SB)/1, $0x40
DATA d_cUlo<>+12(SB)/1, $0x40
DATA d_cUlo<>+13(SB)/1, $0x40
DATA d_cUlo<>+14(SB)/1, $0x40
DATA d_cUlo<>+15(SB)/1, $0x40
GLOBL d_cUlo<>(SB), RODATA|NOPTR, $16

DATA d_cUhi<>+0(SB)/1, $0x47
DATA d_cUhi<>+1(SB)/1, $0x47
DATA d_cUhi<>+2(SB)/1, $0x47
DATA d_cUhi<>+3(SB)/1, $0x47
DATA d_cUhi<>+4(SB)/1, $0x47
DATA d_cUhi<>+5(SB)/1, $0x47
DATA d_cUhi<>+6(SB)/1, $0x47
DATA d_cUhi<>+7(SB)/1, $0x47
DATA d_cUhi<>+8(SB)/1, $0x47
DATA d_cUhi<>+9(SB)/1, $0x47
DATA d_cUhi<>+10(SB)/1, $0x47
DATA d_cUhi<>+11(SB)/1, $0x47
DATA d_cUhi<>+12(SB)/1, $0x47
DATA d_cUhi<>+13(SB)/1, $0x47
DATA d_cUhi<>+14(SB)/1, $0x47
DATA d_cUhi<>+15(SB)/1, $0x47
GLOBL d_cUhi<>(SB), RODATA|NOPTR, $16

DATA d_cLlo<>+0(SB)/1, $0x60
DATA d_cLlo<>+1(SB)/1, $0x60
DATA d_cLlo<>+2(SB)/1, $0x60
DATA d_cLlo<>+3(SB)/1, $0x60
DATA d_cLlo<>+4(SB)/1, $0x60
DATA d_cLlo<>+5(SB)/1, $0x60
DATA d_cLlo<>+6(SB)/1, $0x60
DATA d_cLlo<>+7(SB)/1, $0x60
DATA d_cLlo<>+8(SB)/1, $0x60
DATA d_cLlo<>+9(SB)/1, $0x60
DATA d_cLlo<>+10(SB)/1, $0x60
DATA d_cLlo<>+11(SB)/1, $0x60
DATA d_cLlo<>+12(SB)/1, $0x60
DATA d_cLlo<>+13(SB)/1, $0x60
DATA d_cLlo<>+14(SB)/1, $0x60
DATA d_cLlo<>+15(SB)/1, $0x60
GLOBL d_cLlo<>(SB), RODATA|NOPTR, $16

DATA d_cLhi<>+0(SB)/1, $0x67
DATA d_cLhi<>+1(SB)/1, $0x67
DATA d_cLhi<>+2(SB)/1, $0x67
DATA d_cLhi<>+3(SB)/1, $0x67
DATA d_cLhi<>+4(SB)/1, $0x67
DATA d_cLhi<>+5(SB)/1, $0x67
DATA d_cLhi<>+6(SB)/1, $0x67
DATA d_cLhi<>+7(SB)/1, $0x67
DATA d_cLhi<>+8(SB)/1, $0x67
DATA d_cLhi<>+9(SB)/1, $0x67
DATA d_cLhi<>+10(SB)/1, $0x67
DATA d_cLhi<>+11(SB)/1, $0x67
DATA d_cLhi<>+12(SB)/1, $0x67
DATA d_cLhi<>+13(SB)/1, $0x67
DATA d_cLhi<>+14(SB)/1, $0x67
DATA d_cLhi<>+15(SB)/1, $0x67
GLOBL d_cLhi<>(SB), RODATA|NOPTR, $16

DATA d_subD<>+0(SB)/1, $0x30
DATA d_subD<>+1(SB)/1, $0x30
DATA d_subD<>+2(SB)/1, $0x30
DATA d_subD<>+3(SB)/1, $0x30
DATA d_subD<>+4(SB)/1, $0x30
DATA d_subD<>+5(SB)/1, $0x30
DATA d_subD<>+6(SB)/1, $0x30
DATA d_subD<>+7(SB)/1, $0x30
DATA d_subD<>+8(SB)/1, $0x30
DATA d_subD<>+9(SB)/1, $0x30
DATA d_subD<>+10(SB)/1, $0x30
DATA d_subD<>+11(SB)/1, $0x30
DATA d_subD<>+12(SB)/1, $0x30
DATA d_subD<>+13(SB)/1, $0x30
DATA d_subD<>+14(SB)/1, $0x30
DATA d_subD<>+15(SB)/1, $0x30
GLOBL d_subD<>(SB), RODATA|NOPTR, $16

DATA d_subU<>+0(SB)/1, $0x37
DATA d_subU<>+1(SB)/1, $0x37
DATA d_subU<>+2(SB)/1, $0x37
DATA d_subU<>+3(SB)/1, $0x37
DATA d_subU<>+4(SB)/1, $0x37
DATA d_subU<>+5(SB)/1, $0x37
DATA d_subU<>+6(SB)/1, $0x37
DATA d_subU<>+7(SB)/1, $0x37
DATA d_subU<>+8(SB)/1, $0x37
DATA d_subU<>+9(SB)/1, $0x37
DATA d_subU<>+10(SB)/1, $0x37
DATA d_subU<>+11(SB)/1, $0x37
DATA d_subU<>+12(SB)/1, $0x37
DATA d_subU<>+13(SB)/1, $0x37
DATA d_subU<>+14(SB)/1, $0x37
DATA d_subU<>+15(SB)/1, $0x37
GLOBL d_subU<>(SB), RODATA|NOPTR, $16

DATA d_subL<>+0(SB)/1, $0x57
DATA d_subL<>+1(SB)/1, $0x57
DATA d_subL<>+2(SB)/1, $0x57
DATA d_subL<>+3(SB)/1, $0x57
DATA d_subL<>+4(SB)/1, $0x57
DATA d_subL<>+5(SB)/1, $0x57
DATA d_subL<>+6(SB)/1, $0x57
DATA d_subL<>+7(SB)/1, $0x57
DATA d_subL<>+8(SB)/1, $0x57
DATA d_subL<>+9(SB)/1, $0x57
DATA d_subL<>+10(SB)/1, $0x57
DATA d_subL<>+11(SB)/1, $0x57
DATA d_subL<>+12(SB)/1, $0x57
DATA d_subL<>+13(SB)/1, $0x57
DATA d_subL<>+14(SB)/1, $0x57
DATA d_subL<>+15(SB)/1, $0x57
GLOBL d_subL<>(SB), RODATA|NOPTR, $16

DATA d_four<>+0(SB)/1, $0x04
DATA d_four<>+1(SB)/1, $0x04
DATA d_four<>+2(SB)/1, $0x04
DATA d_four<>+3(SB)/1, $0x04
DATA d_four<>+4(SB)/1, $0x04
DATA d_four<>+5(SB)/1, $0x04
DATA d_four<>+6(SB)/1, $0x04
DATA d_four<>+7(SB)/1, $0x04
DATA d_four<>+8(SB)/1, $0x04
DATA d_four<>+9(SB)/1, $0x04
DATA d_four<>+10(SB)/1, $0x04
DATA d_four<>+11(SB)/1, $0x04
DATA d_four<>+12(SB)/1, $0x04
DATA d_four<>+13(SB)/1, $0x04
DATA d_four<>+14(SB)/1, $0x04
DATA d_four<>+15(SB)/1, $0x04
GLOBL d_four<>(SB), RODATA|NOPTR, $16

DATA d_gHi<>+0(SB)/1, $0x00
DATA d_gHi<>+1(SB)/1, $0x02
DATA d_gHi<>+2(SB)/1, $0x04
DATA d_gHi<>+3(SB)/1, $0x06
DATA d_gHi<>+4(SB)/1, $0x08
DATA d_gHi<>+5(SB)/1, $0x0a
DATA d_gHi<>+6(SB)/1, $0x0c
DATA d_gHi<>+7(SB)/1, $0x0e
DATA d_gHi<>+8(SB)/1, $0x10
DATA d_gHi<>+9(SB)/1, $0x12
DATA d_gHi<>+10(SB)/1, $0x14
DATA d_gHi<>+11(SB)/1, $0x16
DATA d_gHi<>+12(SB)/1, $0x18
DATA d_gHi<>+13(SB)/1, $0x1a
DATA d_gHi<>+14(SB)/1, $0x1c
DATA d_gHi<>+15(SB)/1, $0x1e
GLOBL d_gHi<>(SB), RODATA|NOPTR, $16

DATA d_gLo<>+0(SB)/1, $0x01
DATA d_gLo<>+1(SB)/1, $0x03
DATA d_gLo<>+2(SB)/1, $0x05
DATA d_gLo<>+3(SB)/1, $0x07
DATA d_gLo<>+4(SB)/1, $0x09
DATA d_gLo<>+5(SB)/1, $0x0b
DATA d_gLo<>+6(SB)/1, $0x0d
DATA d_gLo<>+7(SB)/1, $0x0f
DATA d_gLo<>+8(SB)/1, $0x11
DATA d_gLo<>+9(SB)/1, $0x13
DATA d_gLo<>+10(SB)/1, $0x15
DATA d_gLo<>+11(SB)/1, $0x17
DATA d_gLo<>+12(SB)/1, $0x19
DATA d_gLo<>+13(SB)/1, $0x1b
DATA d_gLo<>+14(SB)/1, $0x1d
DATA d_gLo<>+15(SB)/1, $0x1f
GLOBL d_gLo<>(SB), RODATA|NOPTR, $16

