//go:build ppc64le

package hex

import "golang.org/x/sys/cpu"

// hasVSX gates the ppc64le VSX kernels (both encode and decode). The generated
// kernels emit ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X) that raise SIGILL
// on POWER8, so they run only when the CPU is POWER9+; on POWER8 encodeSIMD and
// decodeSIMD report no progress and the stdlib-style scalar path does all the
// work. It is a var (not a const) so the dispatch test can force the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

// encodeBlocksVSX encodes whole 16-byte source blocks into 32 hex chars each,
// using the ppc64le VSX/AltiVec kernel generated by go-asmgen
// (encode_ppc64le_gen.go), in encode_ppc64le.s. It emits ISA-3.0 (POWER9)
// instructions (LXVB16X/STXVB16X) that SIGILL on POWER8, so callers must gate it
// behind hasVSX (cpu.PPC64.IsPOWER9).
func encodeBlocksVSX(dst, src []byte, n int)

// encodeSIMD runs the VSX kernel over whole 16-byte source blocks and reports
// the bytes consumed in src and written in dst so the caller finishes the tail
// with the standard library. On a pre-POWER9 CPU it reports no progress so the
// whole input goes to the scalar path.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if hasVSX && n >= 16 {
		blocks := n / 16
		encodeBlocksVSX(dst, src, blocks)
		return blocks * 16, blocks * 32
	}
	return 0, 0
}
