//go:build arm64

package hex

// encodeBlocks encodes n blocks of 16 source bytes into 32 lowercase hex chars
// each via NEON: a nibble split (VUSHR/VAND), a 16-byte VTBL nibble->ASCII
// lookup per nibble stream, and a VST2 interleaving store that lands each byte's
// (hi,lo) chars adjacent. Generated by go-asmgen (encode_arm64_gen.go), in
// encode_arm64.s.
func encodeBlocks(dst, src []byte, n int)

// encodeSIMD runs encodeBlocks over whole 16-byte source blocks and reports the
// bytes consumed in src and written in dst so the caller finishes the tail with
// the standard library.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	if len(src) < 16 {
		return 0, 0
	}
	blocks := len(src) / 16
	encodeBlocks(dst, src, blocks)
	return blocks * 16, blocks * 32
}
