// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·encodeBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $earmLut<>(SB), R3
	VLD1 (R3), [V8.B16]
	VMOVI $15, V9.B16
	CBZ R2, done
loop:
	VLD1.P 16(R1), [V0.B16]
	VUSHR $4, V0.B16, V1.B16
	VAND V9.B16, V0.B16, V2.B16
	VTBL V1.B16, [V8.B16], V3.B16
	VTBL V2.B16, [V8.B16], V4.B16
	VST2.P [V3.B16, V4.B16], 32(R0)
	SUB $1, R2
	CBNZ R2, loop
done:
	RET

DATA earmLut<>+0(SB)/1, $0x30
DATA earmLut<>+1(SB)/1, $0x31
DATA earmLut<>+2(SB)/1, $0x32
DATA earmLut<>+3(SB)/1, $0x33
DATA earmLut<>+4(SB)/1, $0x34
DATA earmLut<>+5(SB)/1, $0x35
DATA earmLut<>+6(SB)/1, $0x36
DATA earmLut<>+7(SB)/1, $0x37
DATA earmLut<>+8(SB)/1, $0x38
DATA earmLut<>+9(SB)/1, $0x39
DATA earmLut<>+10(SB)/1, $0x61
DATA earmLut<>+11(SB)/1, $0x62
DATA earmLut<>+12(SB)/1, $0x63
DATA earmLut<>+13(SB)/1, $0x64
DATA earmLut<>+14(SB)/1, $0x65
DATA earmLut<>+15(SB)/1, $0x66
GLOBL earmLut<>(SB), RODATA|NOPTR, $16

