//go:build s390x

package hex

// encodeBlocksVX encodes whole 16-byte source blocks into 32 hex chars each,
// using the s390x vector-facility kernel generated by go-asmgen
// (encode_s390x_gen.go), in encode_s390x.s.
func encodeBlocksVX(dst, src []byte, n int)

// encodeSIMD runs the vector kernel over whole 16-byte source blocks and reports
// the bytes consumed in src and written in dst so the caller finishes the tail
// with the standard library.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n >= 16 {
		blocks := n / 16
		encodeBlocksVX(dst, src, blocks)
		return blocks * 16, blocks * 32
	}
	return 0, 0
}
