// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·encodeBlocksVSX(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $hexlut_p<>+0(SB), R6
	MOVD $lomask_p<>+0(SB), R7
	MOVD $four_p<>+0(SB), R8
	MOVD $ctrlLo_p<>+0(SB), R9
	MOVD $ctrlHi_p<>+0(SB), R10
	LXVB16X (R0)(R6), VS33
	LXVB16X (R0)(R7), VS34
	LXVB16X (R0)(R8), VS35
	LXVB16X (R0)(R9), VS36
	LXVB16X (R0)(R10), VS37
	CMP R5, $0
	BEQ edone
	MOVD $0, R11
	MOVD $0, R12
eloop:
	LXVB16X (R11)(R4), VS32
	VAND V0, V2, V6
	VSRB V0, V3, V7
	VPERM V1, V1, V7, V8
	VPERM V1, V1, V6, V9
	VPERM V8, V9, V4, V10
	VPERM V8, V9, V5, V11
	STXVB16X VS42, (R12)(R3)
	ADD $16, R12
	STXVB16X VS43, (R12)(R3)
	ADD $16, R11
	ADD $16, R12
	ADD $-1, R5
	CMP R5, $0
	BNE eloop
edone:
	RET

DATA hexlut_p<>+0(SB)/1, $0x30
DATA hexlut_p<>+1(SB)/1, $0x31
DATA hexlut_p<>+2(SB)/1, $0x32
DATA hexlut_p<>+3(SB)/1, $0x33
DATA hexlut_p<>+4(SB)/1, $0x34
DATA hexlut_p<>+5(SB)/1, $0x35
DATA hexlut_p<>+6(SB)/1, $0x36
DATA hexlut_p<>+7(SB)/1, $0x37
DATA hexlut_p<>+8(SB)/1, $0x38
DATA hexlut_p<>+9(SB)/1, $0x39
DATA hexlut_p<>+10(SB)/1, $0x61
DATA hexlut_p<>+11(SB)/1, $0x62
DATA hexlut_p<>+12(SB)/1, $0x63
DATA hexlut_p<>+13(SB)/1, $0x64
DATA hexlut_p<>+14(SB)/1, $0x65
DATA hexlut_p<>+15(SB)/1, $0x66
GLOBL hexlut_p<>(SB), RODATA|NOPTR, $16

DATA lomask_p<>+0(SB)/1, $0x0f
DATA lomask_p<>+1(SB)/1, $0x0f
DATA lomask_p<>+2(SB)/1, $0x0f
DATA lomask_p<>+3(SB)/1, $0x0f
DATA lomask_p<>+4(SB)/1, $0x0f
DATA lomask_p<>+5(SB)/1, $0x0f
DATA lomask_p<>+6(SB)/1, $0x0f
DATA lomask_p<>+7(SB)/1, $0x0f
DATA lomask_p<>+8(SB)/1, $0x0f
DATA lomask_p<>+9(SB)/1, $0x0f
DATA lomask_p<>+10(SB)/1, $0x0f
DATA lomask_p<>+11(SB)/1, $0x0f
DATA lomask_p<>+12(SB)/1, $0x0f
DATA lomask_p<>+13(SB)/1, $0x0f
DATA lomask_p<>+14(SB)/1, $0x0f
DATA lomask_p<>+15(SB)/1, $0x0f
GLOBL lomask_p<>(SB), RODATA|NOPTR, $16

DATA four_p<>+0(SB)/1, $0x04
DATA four_p<>+1(SB)/1, $0x04
DATA four_p<>+2(SB)/1, $0x04
DATA four_p<>+3(SB)/1, $0x04
DATA four_p<>+4(SB)/1, $0x04
DATA four_p<>+5(SB)/1, $0x04
DATA four_p<>+6(SB)/1, $0x04
DATA four_p<>+7(SB)/1, $0x04
DATA four_p<>+8(SB)/1, $0x04
DATA four_p<>+9(SB)/1, $0x04
DATA four_p<>+10(SB)/1, $0x04
DATA four_p<>+11(SB)/1, $0x04
DATA four_p<>+12(SB)/1, $0x04
DATA four_p<>+13(SB)/1, $0x04
DATA four_p<>+14(SB)/1, $0x04
DATA four_p<>+15(SB)/1, $0x04
GLOBL four_p<>(SB), RODATA|NOPTR, $16

DATA ctrlLo_p<>+0(SB)/1, $0x00
DATA ctrlLo_p<>+1(SB)/1, $0x10
DATA ctrlLo_p<>+2(SB)/1, $0x01
DATA ctrlLo_p<>+3(SB)/1, $0x11
DATA ctrlLo_p<>+4(SB)/1, $0x02
DATA ctrlLo_p<>+5(SB)/1, $0x12
DATA ctrlLo_p<>+6(SB)/1, $0x03
DATA ctrlLo_p<>+7(SB)/1, $0x13
DATA ctrlLo_p<>+8(SB)/1, $0x04
DATA ctrlLo_p<>+9(SB)/1, $0x14
DATA ctrlLo_p<>+10(SB)/1, $0x05
DATA ctrlLo_p<>+11(SB)/1, $0x15
DATA ctrlLo_p<>+12(SB)/1, $0x06
DATA ctrlLo_p<>+13(SB)/1, $0x16
DATA ctrlLo_p<>+14(SB)/1, $0x07
DATA ctrlLo_p<>+15(SB)/1, $0x17
GLOBL ctrlLo_p<>(SB), RODATA|NOPTR, $16

DATA ctrlHi_p<>+0(SB)/1, $0x08
DATA ctrlHi_p<>+1(SB)/1, $0x18
DATA ctrlHi_p<>+2(SB)/1, $0x09
DATA ctrlHi_p<>+3(SB)/1, $0x19
DATA ctrlHi_p<>+4(SB)/1, $0x0a
DATA ctrlHi_p<>+5(SB)/1, $0x1a
DATA ctrlHi_p<>+6(SB)/1, $0x0b
DATA ctrlHi_p<>+7(SB)/1, $0x1b
DATA ctrlHi_p<>+8(SB)/1, $0x0c
DATA ctrlHi_p<>+9(SB)/1, $0x1c
DATA ctrlHi_p<>+10(SB)/1, $0x0d
DATA ctrlHi_p<>+11(SB)/1, $0x1d
DATA ctrlHi_p<>+12(SB)/1, $0x0e
DATA ctrlHi_p<>+13(SB)/1, $0x1e
DATA ctrlHi_p<>+14(SB)/1, $0x0f
DATA ctrlHi_p<>+15(SB)/1, $0x1f
GLOBL ctrlHi_p<>(SB), RODATA|NOPTR, $16

