// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·encodeBlocksSSE(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU hexlut<>+0(SB), X7
	MOVOU lomask<>+0(SB), X8
	TESTQ CX, CX
	JZ sdone
sloop:
	MOVOU (SI), X0
	MOVO X0, X1
	PSRLW $4, X0
	PAND X8, X0
	PAND X8, X1
	MOVO X7, X2
	PSHUFB X0, X2
	MOVO X7, X3
	PSHUFB X1, X3
	MOVO X2, X4
	PUNPCKLBW X3, X4
	PUNPCKHBW X3, X2
	MOVOU X4, (DI)
	MOVOU X2, 16(DI)
	ADDQ $16, SI
	ADDQ $32, DI
	DECQ CX
	JNZ sloop
sdone:
	RET

TEXT ·encodeBlocksAVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU hexlutb<>+0(SB), Y7
	VMOVDQU lomaskb<>+0(SB), Y8
	TESTQ CX, CX
	JZ vdone
vloop:
	VMOVDQU (SI), Y0
	VPSRLW $4, Y0, Y1
	VPAND Y8, Y1, Y1
	VPAND Y8, Y0, Y0
	VPSHUFB Y1, Y7, Y1
	VPSHUFB Y0, Y7, Y0
	VPUNPCKLBW Y0, Y1, Y2
	VPUNPCKHBW Y0, Y1, Y3
	VPERM2I128 $0x20, Y3, Y2, Y4
	VPERM2I128 $0x31, Y3, Y2, Y5
	VMOVDQU Y4, (DI)
	VMOVDQU Y5, 32(DI)
	ADDQ $32, SI
	ADDQ $64, DI
	DECQ CX
	JNZ vloop
vdone:
	VZEROUPPER
	RET

DATA hexlut<>+0(SB)/1, $0x30
DATA hexlut<>+1(SB)/1, $0x31
DATA hexlut<>+2(SB)/1, $0x32
DATA hexlut<>+3(SB)/1, $0x33
DATA hexlut<>+4(SB)/1, $0x34
DATA hexlut<>+5(SB)/1, $0x35
DATA hexlut<>+6(SB)/1, $0x36
DATA hexlut<>+7(SB)/1, $0x37
DATA hexlut<>+8(SB)/1, $0x38
DATA hexlut<>+9(SB)/1, $0x39
DATA hexlut<>+10(SB)/1, $0x61
DATA hexlut<>+11(SB)/1, $0x62
DATA hexlut<>+12(SB)/1, $0x63
DATA hexlut<>+13(SB)/1, $0x64
DATA hexlut<>+14(SB)/1, $0x65
DATA hexlut<>+15(SB)/1, $0x66
GLOBL hexlut<>(SB), RODATA|NOPTR, $16

DATA lomask<>+0(SB)/1, $0x0f
DATA lomask<>+1(SB)/1, $0x0f
DATA lomask<>+2(SB)/1, $0x0f
DATA lomask<>+3(SB)/1, $0x0f
DATA lomask<>+4(SB)/1, $0x0f
DATA lomask<>+5(SB)/1, $0x0f
DATA lomask<>+6(SB)/1, $0x0f
DATA lomask<>+7(SB)/1, $0x0f
DATA lomask<>+8(SB)/1, $0x0f
DATA lomask<>+9(SB)/1, $0x0f
DATA lomask<>+10(SB)/1, $0x0f
DATA lomask<>+11(SB)/1, $0x0f
DATA lomask<>+12(SB)/1, $0x0f
DATA lomask<>+13(SB)/1, $0x0f
DATA lomask<>+14(SB)/1, $0x0f
DATA lomask<>+15(SB)/1, $0x0f
GLOBL lomask<>(SB), RODATA|NOPTR, $16

DATA hexlutb<>+0(SB)/1, $0x30
DATA hexlutb<>+1(SB)/1, $0x31
DATA hexlutb<>+2(SB)/1, $0x32
DATA hexlutb<>+3(SB)/1, $0x33
DATA hexlutb<>+4(SB)/1, $0x34
DATA hexlutb<>+5(SB)/1, $0x35
DATA hexlutb<>+6(SB)/1, $0x36
DATA hexlutb<>+7(SB)/1, $0x37
DATA hexlutb<>+8(SB)/1, $0x38
DATA hexlutb<>+9(SB)/1, $0x39
DATA hexlutb<>+10(SB)/1, $0x61
DATA hexlutb<>+11(SB)/1, $0x62
DATA hexlutb<>+12(SB)/1, $0x63
DATA hexlutb<>+13(SB)/1, $0x64
DATA hexlutb<>+14(SB)/1, $0x65
DATA hexlutb<>+15(SB)/1, $0x66
DATA hexlutb<>+16(SB)/1, $0x30
DATA hexlutb<>+17(SB)/1, $0x31
DATA hexlutb<>+18(SB)/1, $0x32
DATA hexlutb<>+19(SB)/1, $0x33
DATA hexlutb<>+20(SB)/1, $0x34
DATA hexlutb<>+21(SB)/1, $0x35
DATA hexlutb<>+22(SB)/1, $0x36
DATA hexlutb<>+23(SB)/1, $0x37
DATA hexlutb<>+24(SB)/1, $0x38
DATA hexlutb<>+25(SB)/1, $0x39
DATA hexlutb<>+26(SB)/1, $0x61
DATA hexlutb<>+27(SB)/1, $0x62
DATA hexlutb<>+28(SB)/1, $0x63
DATA hexlutb<>+29(SB)/1, $0x64
DATA hexlutb<>+30(SB)/1, $0x65
DATA hexlutb<>+31(SB)/1, $0x66
GLOBL hexlutb<>(SB), RODATA|NOPTR, $32

DATA lomaskb<>+0(SB)/1, $0x0f
DATA lomaskb<>+1(SB)/1, $0x0f
DATA lomaskb<>+2(SB)/1, $0x0f
DATA lomaskb<>+3(SB)/1, $0x0f
DATA lomaskb<>+4(SB)/1, $0x0f
DATA lomaskb<>+5(SB)/1, $0x0f
DATA lomaskb<>+6(SB)/1, $0x0f
DATA lomaskb<>+7(SB)/1, $0x0f
DATA lomaskb<>+8(SB)/1, $0x0f
DATA lomaskb<>+9(SB)/1, $0x0f
DATA lomaskb<>+10(SB)/1, $0x0f
DATA lomaskb<>+11(SB)/1, $0x0f
DATA lomaskb<>+12(SB)/1, $0x0f
DATA lomaskb<>+13(SB)/1, $0x0f
DATA lomaskb<>+14(SB)/1, $0x0f
DATA lomaskb<>+15(SB)/1, $0x0f
DATA lomaskb<>+16(SB)/1, $0x0f
DATA lomaskb<>+17(SB)/1, $0x0f
DATA lomaskb<>+18(SB)/1, $0x0f
DATA lomaskb<>+19(SB)/1, $0x0f
DATA lomaskb<>+20(SB)/1, $0x0f
DATA lomaskb<>+21(SB)/1, $0x0f
DATA lomaskb<>+22(SB)/1, $0x0f
DATA lomaskb<>+23(SB)/1, $0x0f
DATA lomaskb<>+24(SB)/1, $0x0f
DATA lomaskb<>+25(SB)/1, $0x0f
DATA lomaskb<>+26(SB)/1, $0x0f
DATA lomaskb<>+27(SB)/1, $0x0f
DATA lomaskb<>+28(SB)/1, $0x0f
DATA lomaskb<>+29(SB)/1, $0x0f
DATA lomaskb<>+30(SB)/1, $0x0f
DATA lomaskb<>+31(SB)/1, $0x0f
GLOBL lomaskb<>(SB), RODATA|NOPTR, $32

