//go:build ppc64le

package hex

// encodeBlocksVSX encodes whole 16-byte source blocks into 32 hex chars each,
// using the ppc64le VSX/AltiVec kernel generated by go-asmgen
// (encode_ppc64le_gen.go), in encode_ppc64le.s. VSX is part of the ppc64le
// baseline (POWER8+), so no runtime feature check is needed.
func encodeBlocksVSX(dst, src []byte, n int)

// encodeSIMD runs the VSX kernel over whole 16-byte source blocks and reports
// the bytes consumed in src and written in dst so the caller finishes the tail
// with the standard library.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n >= 16 {
		blocks := n / 16
		encodeBlocksVSX(dst, src, blocks)
		return blocks * 16, blocks * 32
	}
	return 0, 0
}
