//go:build amd64

package hex

import "golang.org/x/sys/cpu"

// encodeBlocksSSE (16 src bytes -> 32 hex chars per block) and encodeBlocksAVX2
// (32 -> 64) are the vectorised hex encoders. Generated by go-asmgen
// (encode_gen.go), in encode_amd64.s.
func encodeBlocksSSE(dst, src []byte, n int)
func encodeBlocksAVX2(dst, src []byte, n int)

var hasAVX2 = cpu.X86.HasAVX2

// encodeSIMD runs the widest available kernel over whole 16- or 32-byte source
// blocks and reports the bytes consumed in src and written in dst so the caller
// finishes the tail with the standard library.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		encodeBlocksAVX2(dst, src, blocks)
		return blocks * 32, blocks * 64
	}
	if n >= 16 {
		blocks := n / 16
		encodeBlocksSSE(dst, src, blocks)
		return blocks * 16, blocks * 32
	}
	return 0, 0
}
