// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·encodeBlocksVX(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	MOVD $hexlut_z<>+0(SB), R5
	VL (R5), V1
	MOVD $lomask_z<>+0(SB), R5
	VL (R5), V2
	MOVD $ctrlLo_z<>+0(SB), R5
	VL (R5), V4
	MOVD $ctrlHi_z<>+0(SB), R5
	VL (R5), V5
	CMPBEQ R3, $0, edone
eloop:
	VL (R2), V0
	VN V0, V2, V6
	VESRLB $4, V0, V7
	VPERM V1, V1, V7, V8
	VPERM V1, V1, V6, V9
	VPERM V8, V9, V4, V10
	VPERM V8, V9, V5, V11
	VST V10, (R1)
	VST V11, 16(R1)
	ADD $16, R2
	ADD $32, R1
	ADD $-1, R3
	CMPBNE R3, $0, eloop
edone:
	RET

DATA hexlut_z<>+0(SB)/1, $0x30
DATA hexlut_z<>+1(SB)/1, $0x31
DATA hexlut_z<>+2(SB)/1, $0x32
DATA hexlut_z<>+3(SB)/1, $0x33
DATA hexlut_z<>+4(SB)/1, $0x34
DATA hexlut_z<>+5(SB)/1, $0x35
DATA hexlut_z<>+6(SB)/1, $0x36
DATA hexlut_z<>+7(SB)/1, $0x37
DATA hexlut_z<>+8(SB)/1, $0x38
DATA hexlut_z<>+9(SB)/1, $0x39
DATA hexlut_z<>+10(SB)/1, $0x61
DATA hexlut_z<>+11(SB)/1, $0x62
DATA hexlut_z<>+12(SB)/1, $0x63
DATA hexlut_z<>+13(SB)/1, $0x64
DATA hexlut_z<>+14(SB)/1, $0x65
DATA hexlut_z<>+15(SB)/1, $0x66
GLOBL hexlut_z<>(SB), RODATA|NOPTR, $16

DATA lomask_z<>+0(SB)/1, $0x0f
DATA lomask_z<>+1(SB)/1, $0x0f
DATA lomask_z<>+2(SB)/1, $0x0f
DATA lomask_z<>+3(SB)/1, $0x0f
DATA lomask_z<>+4(SB)/1, $0x0f
DATA lomask_z<>+5(SB)/1, $0x0f
DATA lomask_z<>+6(SB)/1, $0x0f
DATA lomask_z<>+7(SB)/1, $0x0f
DATA lomask_z<>+8(SB)/1, $0x0f
DATA lomask_z<>+9(SB)/1, $0x0f
DATA lomask_z<>+10(SB)/1, $0x0f
DATA lomask_z<>+11(SB)/1, $0x0f
DATA lomask_z<>+12(SB)/1, $0x0f
DATA lomask_z<>+13(SB)/1, $0x0f
DATA lomask_z<>+14(SB)/1, $0x0f
DATA lomask_z<>+15(SB)/1, $0x0f
GLOBL lomask_z<>(SB), RODATA|NOPTR, $16

DATA ctrlLo_z<>+0(SB)/1, $0x00
DATA ctrlLo_z<>+1(SB)/1, $0x10
DATA ctrlLo_z<>+2(SB)/1, $0x01
DATA ctrlLo_z<>+3(SB)/1, $0x11
DATA ctrlLo_z<>+4(SB)/1, $0x02
DATA ctrlLo_z<>+5(SB)/1, $0x12
DATA ctrlLo_z<>+6(SB)/1, $0x03
DATA ctrlLo_z<>+7(SB)/1, $0x13
DATA ctrlLo_z<>+8(SB)/1, $0x04
DATA ctrlLo_z<>+9(SB)/1, $0x14
DATA ctrlLo_z<>+10(SB)/1, $0x05
DATA ctrlLo_z<>+11(SB)/1, $0x15
DATA ctrlLo_z<>+12(SB)/1, $0x06
DATA ctrlLo_z<>+13(SB)/1, $0x16
DATA ctrlLo_z<>+14(SB)/1, $0x07
DATA ctrlLo_z<>+15(SB)/1, $0x17
GLOBL ctrlLo_z<>(SB), RODATA|NOPTR, $16

DATA ctrlHi_z<>+0(SB)/1, $0x08
DATA ctrlHi_z<>+1(SB)/1, $0x18
DATA ctrlHi_z<>+2(SB)/1, $0x09
DATA ctrlHi_z<>+3(SB)/1, $0x19
DATA ctrlHi_z<>+4(SB)/1, $0x0a
DATA ctrlHi_z<>+5(SB)/1, $0x1a
DATA ctrlHi_z<>+6(SB)/1, $0x0b
DATA ctrlHi_z<>+7(SB)/1, $0x1b
DATA ctrlHi_z<>+8(SB)/1, $0x0c
DATA ctrlHi_z<>+9(SB)/1, $0x1c
DATA ctrlHi_z<>+10(SB)/1, $0x0d
DATA ctrlHi_z<>+11(SB)/1, $0x1d
DATA ctrlHi_z<>+12(SB)/1, $0x0e
DATA ctrlHi_z<>+13(SB)/1, $0x1e
DATA ctrlHi_z<>+14(SB)/1, $0x0f
DATA ctrlHi_z<>+15(SB)/1, $0x1f
GLOBL ctrlHi_z<>(SB), RODATA|NOPTR, $16

