// Package hex is a drop-in fast path for lowercase hexadecimal (base16)
// encoding, byte-identical to the standard library's encoding/hex. The bulk of
// encoding runs a SIMD kernel generated by go-asmgen (amd64 SSE2/SSSE3, with an
// AVX2 path; other architectures fall back to the standard library); the short
// tail reuses encoding/hex so output matches exactly.
//
// Decoding currently delegates to encoding/hex (scalar), which makes Decode and
// DecodeString byte-identical to the standard library including the exact
// InvalidByteError / ErrLength errors at the same offsets. A SIMD decode kernel
// is planned.
package hex

import "encoding/hex"

// EncodedLen returns the length of an encoding of n source bytes: exactly 2n.
func EncodedLen(n int) int { return hex.EncodedLen(n) }

// Encode encodes src into EncodedLen(len(src)) bytes of dst, writing lowercase
// hexadecimal. It returns the number of bytes written, len(src)*2. Output is
// identical to encoding/hex.Encode.
func Encode(dst, src []byte) int {
	sd, dd := encodeSIMD(dst, src)
	hex.Encode(dst[dd:], src[sd:])
	return EncodedLen(len(src))
}

// EncodeToString returns the lowercase hexadecimal encoding of src, identical to
// encoding/hex.EncodeToString.
func EncodeToString(src []byte) string {
	dst := make([]byte, EncodedLen(len(src)))
	Encode(dst, src)
	return string(dst)
}

// DecodedLen returns the length of a decoding of n hexadecimal bytes: n/2.
func DecodedLen(n int) int { return hex.DecodedLen(n) }

// Decode decodes src into DecodedLen(len(src)) bytes, returning the number of
// bytes written. It is byte- and error-identical to encoding/hex.Decode
// (scalar; a SIMD decode kernel is planned).
func Decode(dst, src []byte) (int, error) { return hex.Decode(dst, src) }

// DecodeString returns the bytes represented by the hexadecimal string s,
// identical to encoding/hex.DecodeString.
func DecodeString(s string) ([]byte, error) { return hex.DecodeString(s) }
